#!/bin/bash
set -euo pipefail

LOG="/var/log/subscribe/entrypoint.log"
mkdir -p /var/log/subscribe /etc/nginx/subscribe

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [entrypoint] $*" | tee -a "$LOG"; }

[[ -z "${V2B_BACKEND:-}" ]] && { echo "❌ V2B_BACKEND 未设置"; exit 1; }
[[ -z "${V2B_HOST:-}" ]]    && { echo "❌ V2B_HOST 未设置"; exit 1; }

is_valid_trusted_ip() {
    local value="$1"
    local addr="$value"
    local prefix=""
    local o1 o2 o3 o4 octet

    if [[ "$value" == "0.0.0.0/0" || "$value" == "::/0" ]]; then
        return 1
    fi

    if [[ "$value" == */* ]]; then
        addr="${value%/*}"
        prefix="${value#*/}"
        [[ "$prefix" =~ ^[0-9]+$ ]] || return 1
    fi

    if [[ "$addr" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
        if [[ -n "$prefix" ]]; then
            (( 10#$prefix <= 32 )) || return 1
        fi
        IFS='.' read -r o1 o2 o3 o4 <<< "$addr"
        for octet in "$o1" "$o2" "$o3" "$o4"; do
            (( 10#$octet >= 0 && 10#$octet <= 255 )) || return 1
        done
        return 0
    fi

    if [[ "$addr" == *:* ]]; then
        # 逐段校验 IPv6，拒绝畸形地址：否则会被写入 real_ip.conf 导致 nginx 启动失败
        [[ "$addr" =~ ^[0-9A-Fa-f:]+$ ]] || return 1
        case "$addr" in
            *:::*)   return 1 ;;   # 三个及以上连续冒号
            *::*::*) return 1 ;;   # 出现两个 "::"
        esac
        # 单独的前导/末尾冒号（非 "::"）非法
        [[ "$addr" == :* && "$addr" != ::* ]] && return 1
        [[ "$addr" == *: && "$addr" != *:: ]] && return 1
        if [[ -n "$prefix" ]]; then
            (( 10#$prefix <= 128 )) || return 1
        fi
        local -a hextets
        local groups=0 seg
        IFS=':' read -ra hextets <<< "$addr"
        for seg in "${hextets[@]}"; do
            [[ -z "$seg" ]] && continue
            [[ "$seg" =~ ^[0-9A-Fa-f]{1,4}$ ]] || return 1
            groups=$((groups + 1))
        done
        if [[ "$addr" == *::* ]]; then
            (( groups <= 7 )) || return 1
        else
            (( groups == 8 )) || return 1
        fi
        return 0
    fi

    return 1
}

write_real_ip_conf() {
    local output="/etc/nginx/subscribe/real_ip.conf"
    local trusted_ips="${AXISNOW_TRUSTED_IPS:-${REAL_IP_TRUSTED_IPS:-}}"
    local real_ip_header="${REAL_IP_HEADER:-X-Forwarded-For}"
    local normalized count ip
    local -a invalid_ips=()

    if [[ ! "$real_ip_header" =~ ^[A-Za-z0-9-]+$ ]]; then
        log "[警告] REAL_IP_HEADER 不合法，已回退为 X-Forwarded-For"
        real_ip_header="X-Forwarded-For"
    fi

    normalized="${trusted_ips//,/ }"
    normalized="${normalized//;/ }"
    count=0

    {
        echo "# Generated by entrypoint.sh. Do not edit inside the container."
        echo "# Set AXISNOW_TRUSTED_IPS to AxisNow Edge/EIP addresses or CIDRs."

        for ip in $normalized; do
            if is_valid_trusted_ip "$ip"; then
                echo "set_real_ip_from $ip;"
                count=$((count + 1))
            else
                invalid_ips+=("$ip")
            fi
        done

        if [[ "$count" -gt 0 ]]; then
            echo "real_ip_header $real_ip_header;"
            echo "real_ip_recursive on;"
        else
            echo "# No trusted proxy IPs configured; \$remote_addr remains the direct peer IP."
        fi
    } > "$output"

    for ip in "${invalid_ips[@]}"; do
        log "[警告] 跳过不合法的 AXISNOW_TRUSTED_IPS 条目：$ip"
    done

    if [[ "$count" -gt 0 ]]; then
        log "真实客户端 IP 已启用：信任 $count 个回源地址，Header=$real_ip_header"
    else
        log "真实客户端 IP 未启用：未配置 AXISNOW_TRUSTED_IPS"
    fi
}

safe_int() {
    local value="$1" default="$2" min="$3" max="$4"
    if [[ ! "$value" =~ ^[0-9]+$ ]]; then value="$default"; fi
    (( value < min )) && value="$min"
    (( value > max )) && value="$max"
    printf '%s' "$value"
}

safe_bool_01() {
    local value="${1:-}" default="$2"
    case "${value,,}" in
        1|true|yes|on) printf '1' ;;
        0|false|no|off) printf '0' ;;
        *) printf '%s' "$default" ;;
    esac
}

escape_regex_literal() {
    local input="$1" out="" ch
    local i
    for (( i=0; i<${#input}; i++ )); do
        ch="${input:i:1}"
        case "$ch" in
            [\\.^'$'\|\(\)\[\]\*\+\?\/]) out+="\\$ch" ;;
            *) out+="$ch" ;;
        esac
    done
    printf '%s' "$out"
}

write_security_conf() {
    local output="/etc/nginx/subscribe/security.conf"
    local rpm burst waf_enabled auto_enabled auto_rpm auto_burst patterns_raw pattern regex

    rpm=$(safe_int "${SECURITY_RATE_RPM:-10}" 10 1 6000)
    burst=$(safe_int "${SECURITY_RATE_BURST:-5}" 5 0 10000)
    waf_enabled=$(safe_bool_01 "${SECURITY_WAF_ENABLED:-1}" 1)
    auto_enabled=$(safe_bool_01 "${SECURITY_AUTO_BAN_ENABLED:-1}" 1)
    auto_rpm=$(safe_int "${SECURITY_AUTO_BAN_RPM:-3}" 3 1 6000)
    auto_burst=$(safe_int "${SECURITY_AUTO_BAN_BURST:-2}" 2 0 10000)
    patterns_raw="${SECURITY_WAF_PATTERNS:-/cgi-bin/,/etc/passwd,wget,curl,busybox,chmod,eval(,base64_decode}"

    {
        echo "# Generated by entrypoint.sh. WAF blocks/temporarily throttles probes; it does not write permanent firewall deny rules."
        echo "limit_req_zone \$binary_remote_addr zone=subscribe_limit:10m rate=${rpm}r/m;"
        if [[ "$auto_enabled" == "1" ]]; then
            echo "limit_req_zone \$binary_remote_addr zone=waf_probe_limit:10m rate=${auto_rpm}r/m;"
        else
            echo "limit_req_zone \$binary_remote_addr zone=waf_probe_limit:10m rate=6000r/m;"
        fi
        echo "map \$request_uri \$is_bad_request {"
        echo "    default 0;"
        IFS=',;'
        for pattern in $patterns_raw; do
            pattern="${pattern//$'\r'/}"
            pattern="${pattern//$'\n'/}"
            pattern="${pattern#${pattern%%[![:space:]]*}}"
            pattern="${pattern%${pattern##*[![:space:]]}}"
            [[ -z "$pattern" || ${#pattern} -gt 128 ]] && continue
            [[ "$pattern" =~ [\{\}\;\"\`] ]] && continue
            regex=$(escape_regex_literal "$pattern")
            echo "    ~*\"$regex\" 1;"
        done
        unset IFS
        echo "}"
        echo "map \"$waf_enabled\" \$waf_enabled { default $waf_enabled; }"
    } > "$output"

    log "安全配置已生成：订阅限频 ${rpm}r/m burst=${burst}，WAF=${waf_enabled}，临时抑制=${auto_enabled} ${auto_rpm}r/m burst=${auto_burst}"

    export SECURITY_RATE_BURST="$burst"
    export SECURITY_AUTO_BAN_BURST="$auto_burst"
}

log "生成 protect.conf ..."
write_security_conf
envsubst '${V2B_BACKEND} ${V2B_HOST} ${SUBSCRIBE_PATH} ${SECURITY_RATE_BURST} ${SECURITY_AUTO_BAN_BURST}' \
    < /etc/nginx/templates-src/subscribe_protect.conf.template \
    > /etc/nginx/subscribe/protect.conf
chmod 666 /etc/nginx/subscribe/security.conf /etc/nginx/subscribe/protect.conf

write_real_ip_conf

cp /etc/nginx/templates-src/nginx.conf /etc/nginx/nginx.conf

# 初始化空白名单
[[ ! -f /etc/nginx/subscribe/whitelist_ips.txt ]] && touch /etc/nginx/subscribe/whitelist_ips.txt
chmod 666 /etc/nginx/subscribe/whitelist_ips.txt

# 生成白名单 geo 块
SKIP_NGINX_RELOAD=1 /scripts/reload_whitelist.sh

# 初始化空黑名单
[[ ! -f /etc/nginx/subscribe/blacklist.conf ]] && echo "# blacklist" > /etc/nginx/subscribe/blacklist.conf
[[ ! -f /etc/nginx/subscribe/blacklist.json ]] && echo "[]" > /etc/nginx/subscribe/blacklist.json
# 确保 admin 容器可写（admin php-fpm 以非 root 用户运行）
chmod 666 /etc/nginx/subscribe/blacklist.conf /etc/nginx/subscribe/blacklist.json

# 初始化自定义UA封禁
if [[ ! -f /etc/nginx/subscribe/ua_custom.conf ]]; then
    cat > /etc/nginx/subscribe/ua_custom.conf <<'UAEOF'
# 自定义封禁UA - 由 admin 自动生成
map $http_user_agent $is_custom_bad_ua {
    default 0;
}
UAEOF
fi
[[ ! -f /etc/nginx/subscribe/ua_blacklist.json ]] && echo "[]" > /etc/nginx/subscribe/ua_blacklist.json
chmod 666 /etc/nginx/subscribe/ua_custom.conf /etc/nginx/subscribe/ua_blacklist.json

# 初始化UA白名单
if [[ ! -f /etc/nginx/subscribe/ua_whitelist.conf ]]; then
    cat > /etc/nginx/subscribe/ua_whitelist.conf <<'UAWEOF'
# UA白名单 - 由 admin 自动生成
map $http_user_agent $is_ua_whitelisted {
    default 0;
}
UAWEOF
fi
[[ ! -f /etc/nginx/subscribe/ua_whitelist.json ]] && echo "[]" > /etc/nginx/subscribe/ua_whitelist.json
chmod 666 /etc/nginx/subscribe/ua_whitelist.conf /etc/nginx/subscribe/ua_whitelist.json

# 首次拉取云IP库
if [[ ! -f /etc/nginx/subscribe/cloud_geo.conf ]]; then
    log "首次启动：拉取云厂商IP库..."
    SKIP_NGINX_RELOAD=1 /scripts/update_cloud_geo.sh
else
    log "cloud_geo.conf 已存在，跳过初次拉取"
fi

# 每周定时更新
(
    while true; do
        sleep 604800
        log "定时更新云IP库..."
        SKIP_NGINX_RELOAD=0 /scripts/update_cloud_geo.sh || log "[警告] 定时更新失败"
    done
) &

log "启动 nginx reload watcher..."
/scripts/nginx_reload_watcher.sh &

log "启动 nginx..."
exec nginx -g 'daemon off;'
